name: fastai-learning
channels:
  - fastai
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - annotated-types=0.7.0
  - anyio=4.8.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.4
  - attrs=25.1.0
  - babel=2.17.0
  - beautifulsoup4=4.13.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - catalogue=2.0.10
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - cloudpathlib=0.20.0
  - colorama=0.4.6
  - comm=0.2.2
  - confection=0.1.4
  - contourpy=1.3.1
  - cpython=3.10.16
  - cycler=0.12.1
  - cymem=2.0.11
  - cython-blis=1.0.1
  - debugpy=1.8.12
  - decorator=5.1.1
  - defusedxml=0.7.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fastai=2.7.17
  - fastcore=1.7.27
  - fastdownload=0.0.7
  - fastprogress=1.0.3
  - filelock=3.17.0
  - fonttools=4.55.8
  - fqdn=1.5.1
  - freetype=2.12.1
  - fsspec=2025.2.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h11=0.14.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.32.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - joblib=1.4.2
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - langcodes=3.3.0
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240722.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=19.1.7
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libopenblas=0.3.28
  - libpng=1.6.46
  - libprotobuf=5.28.3
  - libsodium=1.0.20
  - libsqlite=3.48.0
  - libtiff=4.7.0
  - libtorch=2.4.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.1.1
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - murmurhash=1.0.10
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nomkl=1.0
  - notebook=7.3.2
  - notebook-shim=0.2.4
  - numpy=2.2.2
  - openjpeg=2.5.3
  - openssl=3.4.0
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - preshed=3.0.9
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - psutil=6.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pydantic=2.10.6
  - pydantic-core=2.27.2
  - pygments=2.19.1
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pyparsing=3.2.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.1
  - python_abi=3.10
  - pytorch=2.4.1
  - pytz=2025.1
  - pyyaml=6.0.2
  - pyzmq=26.2.1
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - rpds-py=0.22.3
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - send2trash=1.8.3
  - setuptools=75.8.0
  - shellingham=1.5.4
  - six=1.17.0
  - sleef=3.8
  - smart-open=7.1.0
  - smart_open=7.1.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - spacy=3.8.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - srsly=2.5.1
  - stack_data=0.6.3
  - sympy=1.13.3
  - terminado=0.18.1
  - thinc=8.3.2
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - torchvision=0.19.1
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typer=0.15.1
  - typer-slim=0.15.1
  - typer-slim-standard=0.15.1
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.3.0
  - wasabi=1.1.2
  - wcwidth=0.2.13
  - weasel=0.4.1
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
prefix: /opt/miniconda3/envs/fastai-learning
